import { Fira_Sans, IBM_Plex_Sans } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Navbar from "../components/layout/navbar";
import Footer from "../components/layout/footer";

const firaSans = Fira_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-fira",
  display: "swap",
});

const ibmPlexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  variable: "--font-ibm",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${firaSans.variable} ${ibmPlexSans.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
        <Script src="/js/flowbite.min.js" strategy="afterInteractive" />
      </body>
    </html>
  );
}
